version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    networks:
      - internal
    expose:
      - "8000"
    environment:
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - FLASK_ENV=${FLASK_ENV}
      - FLASK_DEBUG=${FLASK_DEBUG}
      - DATABASE_URL=${DATABASE_URL}
      - MODEL_PATH=${MODEL_PATH}
    env_file:
      - .env.${FLASK_ENV}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    networks:
      - public
    expose:
      - "80"
    environment:
      - ANGULAR_ENV=${ANGULAR_ENV}
    env_file:
      - .env.${FLASK_ENV}

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - public
      - internal
    environment:
      - NGINX_PORT=${NGINX_PORT}
    env_file:
      - .env.${FLASK_ENV}

networks:
  internal:
    driver: bridge
  public:
    driver: bridge
